name: generate-docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml pandas tabulate

    - name: Run README generation script
      run: |
        mkdir -p pages/datasets
        mkdir -p pages/tags
        python scripts/generate_pages.py

    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Action"
        git pull
        git branch -D static-page || true
        git checkout -b static-page
        git add .
        git commit -m "Auto-Generate Pages [skip ci]"
        git push origin static-page
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
