name: Post Processing OXE dataset

on:
  pull_request:
    branches:
    - main

jobs:
  post-processing:
    # if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install mediapipe
    - name: Install Hugging Face CLI
      run: pip install huggingface-hub

    - name: Download dataset
      run: |
        mkdir -p tmp_dataset
        huggingface-cli download youliangtan/rlds_test_viperx_ds --repo-type dataset --local-dir tmp_dataset

    - name: Run Resharing and Face Blur
      run: |
        python scripts/reshard_rlds.py --rlds_dir tmp_dataset/0.1.0 \
            --output_rlds tmp_dataset/0.1.0 --overwrite --face_blur
        echo "Running post processing script"

    # - name: Upload dataset
    #   run: |
    #     huggingface-cli login
    #     huggingface-cli upload tmp_dataset --token ${{ secrets.HF_TOKEN }}
    #     echo "Uploaded new dataset"
