name: Dataset Verification and Stats Generation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify-and-generate-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run full CI
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        # Internally this runs the verification script and generate stats script
        run: python scripts/run_ci.py | tee full_output.log

      - name: Get last few lines of logs
        # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-output-parameter
        id: last_few_lines
        run: |
          last_10_lines=$(tail -n 10 full_output.log)
          echo "last_10_lines<<EOF" >> $GITHUB_OUTPUT
          echo "$last_10_lines" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          last_2_lines=$(tail -n 2 full_output.log)
          echo "last_2_lines<<EOF" >> $GITHUB_OUTPUT
          echo "$last_2_lines" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
  
      - name: Comment PR
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Show last 10 lines of CI output:
            ```
            ${{ steps.last_few_lines.outputs.last_10_lines }}
            ```

            ---
            
            ${{ steps.last_few_lines.outputs.last_2_lines }}

            Click on the wandb link above to visualize the stats of the first episode
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
