name: Dataset Verification and Stats Generation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify-and-generate-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if specific datasource file has changed
        id: check_changes
        run: |

          # Fetch the latest changes from the origin repository
          git fetch origin main
          git diff --name-only origin/main..HEAD
          
          # Determine if docs/data_sources.yaml has changed
          echo "Checking if docs/index.html has changed..."
          if git diff --name-only origin/main..HEAD | grep -q docs/index.html; then
              echo "File has changed."
              echo "file_changed=true" >> $GITHUB_OUTPUT
          else
              echo "File has not changed."
              echo "file_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Stop job if file(s) not changed
        if: steps.check_changes.outputs.file_changed == 'false'
        run: |
          echo "Stopping the job as the file has not changed."
          exit 0

      - name: Set up Python
        if: steps.check_changes.outputs.file_changed == 'true'
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        if: steps.check_changes.outputs.file_changed == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run full CI
        if: steps.check_changes.outputs.file_changed == 'true'
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        # Internally this runs the verification script and generate stats script
        run: python scripts/run_ci.py | tee full_output.log

      - name: Get last few lines of logs
        if: steps.check_changes.outputs.file_changed == 'true'
        # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-output-parameter
        id: last_few_lines
        run: |
          last_10_lines=$(tail -n 10 full_output.log)
          echo "last_10_lines<<EOF" >> $GITHUB_OUTPUT
          echo "$last_10_lines" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          last_2_lines=$(tail -n 2 full_output.log)
          echo "last_2_lines<<EOF" >> $GITHUB_OUTPUT
          echo "$last_2_lines" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
  
      - name: Comment PR
        if: github.event_name == 'pull_request' && steps.check_changes.outputs.file_changed == 'true'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Show last 10 lines of CI output:
            ```
            ${{ steps.last_few_lines.outputs.last_10_lines }}
            ```

            ---
            
            ${{ steps.last_few_lines.outputs.last_2_lines }}

            Click on the wandb link above to visualize the stats of the first episode
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
